//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExecutionPlanVisualizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgresResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgresResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExecutionPlanVisualizer.PostgresResources", typeof(PostgresResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Font Awesome Free 5.13.0 by @fontawesome - https://fontawesome.com
        /// * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
        /// */
        ///.fa,
        ///.fas,
        ///.far,
        ///.fal,
        ///.fad,
        ///.fab {
        ///  -moz-osx-font-smoothing: grayscale;
        ///  -webkit-font-smoothing: antialiased;
        ///  display: inline-block;
        ///  font-style: normal;
        ///  font-variant: normal;
        ///  text-rendering: auto;
        ///  line-height: 1; }
        ///
        ///.fa-lg {
        ///  font-size: 1.33333em;
        ///  line-height: 0.75em;
        ///  vertical-align: -. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #app,body,html{height:100%}.
        /// </summary>
        internal static string app_css {
            get {
                return ResourceManager.GetString("app_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(t){function e(e){for(var r,i,p=e[0],l=e[1],s=e[2],c=0,f=[];c&lt;p.length;c++)i=p[c],Object.prototype.hasOwnProperty.call(o,i)&amp;&amp;o[i]&amp;&amp;f.push(o[i][0]),o[i]=0;for(r in l)Object.prototype.hasOwnProperty.call(l,r)&amp;&amp;(t[r]=l[r]);a&amp;&amp;a(e);while(f.length)f.shift()();return u.push.apply(u,s||[]),n()}function n(){for(var t,e=0;e&lt;u.length;e++){for(var n=u[e],r=!0,p=1;p&lt;n.length;p++){var l=n[p];0!==o[l]&amp;&amp;(r=!1)}r&amp;&amp;(u.splice(e--,1),t=i(i.s=n[0]))}return t}var r={},o={app:0},u=[];function i(e){if(r[e])return r[e].ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string app_js {
            get {
                return ResourceManager.GetString("app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v4.5.0 (https://getbootstrap.com/)
        /// * Copyright 2011-2020 The Bootstrap Authors
        /// * Copyright 2011-2020 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bootstrap_min {
            get {
                return ResourceManager.GetString("bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (window[&quot;webpackJsonp&quot;]=window[&quot;webpackJsonp&quot;]||[]).push([[&quot;chunk-vendors&quot;],{&quot;00ee&quot;:function(t,e,n){var r=n(&quot;b622&quot;),i=r(&quot;toStringTag&quot;),o={};o[i]=&quot;z&quot;,t.exports=&quot;[object z]&quot;===String(o)},&quot;0366&quot;:function(t,e,n){var r=n(&quot;1c0b&quot;);t.exports=function(t,e,n){if(r(t),void 0===e)return t;switch(n){case 0:return function(){return t.call(e)};case 1:return function(n){return t.call(e,n)};case 2:return function(n,r){return t.call(e,n,r)};case 3:return function(n,r,i){return t.call(e,n,r,i)}}return function(){return t.appl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chunk_vendors {
            get {
                return ResourceManager.GetString("chunk_vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_400 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_4001 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_4001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_4002 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_4002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_4003 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_4003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_brands_4004 {
            get {
                object obj = ResourceManager.GetObject("fa_brands_4004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_400 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_4001 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_4001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_4002 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_4002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_4003 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_4003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_regular_4004 {
            get {
                object obj = ResourceManager.GetObject("fa_regular_4004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_900 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_9001 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_9001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_9002 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_9002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_9003 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_9003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fa_solid_9004 {
            get {
                object obj = ResourceManager.GetObject("fa_solid_9004", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;my-app&lt;/title&gt;
        ///    &lt;link href=&quot;css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;css/all.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;css/app.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///  &lt;link href=&quot;js/app.js&quot; rel=&quot;preload&quot; as=&quot;script&quot;&gt;&lt;link href=&quot;js/chunk-vendors.js&quot; rel=&quot;preload&quot; as=&quot;script&quot;&gt;&lt;/head&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
    }
}
